const {
  DB,
  JWT_SECRET,
  JWT_SECRET_ADMIN,
  JWT_SECRET_USER_INSTITUTION,
  JWT_SECRET_USER_TEACHER,
  JWT_SECRET_USER_STUDENT,
  JWT_SECRET_USER_RESPONSABLE
} = process.env

export const environments = {
  DB: DB!,
  JWT_SECRET: JWT_SECRET!,
  JWT_SECRET_ADMIN: JWT_SECRET_ADMIN!,
  JWT_SECRET_USER_INSTITUTION: JWT_SECRET_USER_INSTITUTION!,
  JWT_SECRET_USER_TEACHER: JWT_SECRET_USER_TEACHER!,
  JWT_SECRET_USER_STUDENT: JWT_SECRET_USER_STUDENT!,
  JWT_SECRET_USER_RESPONSABLE: JWT_SECRET_USER_RESPONSABLE!,
}
