const {
  DB,
  JWT_SECRET,
  JWT_SECRET_ADMIN,
  JWT_SECRET_USER_INSTITUTION,
  JWT_SECRET_USER_TEACHER,
  JWT_SECRET_USER_STUDENT,
  JWT_SECRET_USER_RESPONSABLE
} = process.env

export const environments = {
  DB: DB || 'mongodb://localhost:27017/f8-erp',
  JWT_SECRET: JWT_SECRET || 'secret',
  JWT_SECRET_ADMIN: JWT_SECRET_ADMIN || 'secret',
  JWT_SECRET_USER_INSTITUTION: JWT_SECRET_USER_INSTITUTION || 'secret',
  JWT_SECRET_USER_TEACHER: JWT_SECRET_USER_TEACHER || 'secret',
  JWT_SECRET_USER_STUDENT: JWT_SECRET_USER_STUDENT || 'secret',
  JWT_SECRET_USER_RESPONSABLE: JWT_SECRET_USER_RESPONSABLE || 'secret',
}

export const UserRoles = {
  ADMIN: 'root',
  INSTITUTION: 'institution',
  TEACHER: 'teacher',
  STUDENT: 'student',
  RESPONSABLE: 'responsable'
}